/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hr.obskc.b.niop.gui_ocjena1;

import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class PrviForm extends javax.swing.JFrame {

    /**
     * Creates new form PrviForm
     */
    public PrviForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        odaberiLabel = new javax.swing.JLabel();
        opcijeComboBox = new javax.swing.JComboBox<>();
        prviTextField = new javax.swing.JTextField();
        drugiTextField = new javax.swing.JTextField();
        izracunajButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        drugiLabel = new javax.swing.JLabel();
        treciLabel = new javax.swing.JLabel();
        cetvrtiLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        odaberiLabel.setText("Kalkulator za izracuna udaljenosti, brzine i vremena");

        opcijeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Odaberite opciju", "Udaljenost", "Brzina", "Vrijeme" }));
        opcijeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcijeComboBoxActionPerformed(evt);
            }
        });

        prviTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        prviTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prviTextFieldActionPerformed(evt);
            }
        });

        drugiTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        drugiTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drugiTextFieldActionPerformed(evt);
            }
        });

        izracunajButton.setText("Izracunaj");
        izracunajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izracunajButtonActionPerformed(evt);
            }
        });

        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("REZULTAT:");

        drugiLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        treciLabel.setText("Prva Vrijednost");

        cetvrtiLabel.setText("Druga Vrijednost");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(odaberiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(opcijeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prviTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(drugiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(treciLabel)
                            .addComponent(cetvrtiLabel))
                        .addGap(113, 113, 113)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resetButton)
                            .addComponent(izracunajButton)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(drugiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(odaberiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(opcijeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(izracunajButton))
                        .addGap(30, 30, 30)
                        .addComponent(treciLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(resetButton))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prviTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cetvrtiLabel)
                        .addGap(3, 3, 3)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(drugiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(drugiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opcijeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcijeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcijeComboBoxActionPerformed

    private void drugiTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drugiTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drugiTextFieldActionPerformed

    private void izracunajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izracunajButtonActionPerformed
        
        if(opcijeComboBox.getSelectedItem().equals("Odaberite opciju") || prviTextField.getText().equals("") || drugiTextField.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "morate odabrati opciju i unijeti vrijednosti");
        }
        
        else if(opcijeComboBox.getSelectedItem().equals("Udaljenost"))
        {
            double Brzina = Double.parseDouble(prviTextField.getText());
            double Vrijeme = Double.parseDouble(drugiTextField.getText());
            double Udaljenost = Brzina*Vrijeme;
            
            String value = String.format("%.2f", Udaljenost);
            drugiLabel.setText(value);
        }
        
        else if(opcijeComboBox.getSelectedItem().equals("Brzina"))
        {
            double Udaljenost = Double.parseDouble(prviTextField.getText());
            double Vrijeme = Double.parseDouble(drugiTextField.getText());
            double Brzina = Udaljenost/Vrijeme;
            
            String value = String.format("%.2f", Brzina);
            drugiLabel.setText(value);
        }
        
        else if(opcijeComboBox.getSelectedItem().equals("Vrijeme"))
        {
            double Udaljenost = Double.parseDouble(prviTextField.getText());
            double Brzina = Double.parseDouble(drugiTextField.getText());
            double Vrijeme = Udaljenost/Brzina;
            
            String value = String.format("%.2f", Vrijeme);
            drugiLabel.setText(value);
        }
    }//GEN-LAST:event_izracunajButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        prviTextField.setText("");
        drugiTextField.setText("");
        drugiLabel.setText("");
    }//GEN-LAST:event_resetButtonActionPerformed

    private void prviTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prviTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prviTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrviForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrviForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrviForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrviForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrviForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cetvrtiLabel;
    private javax.swing.JLabel drugiLabel;
    private javax.swing.JTextField drugiTextField;
    private javax.swing.JButton izracunajButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel odaberiLabel;
    private javax.swing.JComboBox<String> opcijeComboBox;
    private javax.swing.JTextField prviTextField;
    private javax.swing.JButton resetButton;
    private javax.swing.JLabel treciLabel;
    // End of variables declaration//GEN-END:variables
}
